version: '3'
services:
  whatsapp-http-api:
    image: devlikeapro/whatsapp-http-api
    container_name: whatsapp-http-api
    ports:
      - '3000:3000/tcp'
    environment:
      # Environment variables from https://waha.devlike.pro/docs/how-to/config/
      - WHATSAPP_HOOK_URL=https://httpbin.org/post
      - WHATSAPP_HOOK_EVENTS=message
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
    restart: always

  whatsapp-http-api-plus:
    image: devlikeapro/whatsapp-http-api-plus
    container_name: whatsapp-http-api-plus
    ports:
      - '3000:3000/tcp'
    volumes:
      - './.sessions:/app/.sessions'
    environment:
      # Environment variables from https://waha.devlike.pro/docs/how-to/config/
      - WHATSAPP_RESTART_ALL_SESSIONS=True
      - WHATSAPP_HOOK_URL=https://httpbin.org/post
      - WHATSAPP_HOOK_EVENTS=message
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
      - WHATSAPP_API_KEY=321
      - WHATSAPP_SWAGGER_USERNAME=khosravan
      - WHATSAPP_SWAGGER_PASSWORD=Khosravan@2024
      - WHATSAPP_API_HOSTNAME=localhost
      WHATSAPP_FILES_LIFETIME=0
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017/tcp'
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: {}
